### ISSUE TITLE
lives: -1

### ISSUE THREAD

**Issue by cakeisalie5** [CoiledSpring/Cafe-Simulator#1]
Hé, faudrait ajouter un menu perdu quand on a perdu (plus de vies).
Et du temps pour rendre ça intéressant.
Et des highscores avec une animation en 3D qui pète et tout.
Et des graphismes.
Et un jeu wesh

**Comment by CoiledSpring** [comment]
Le jeu se ferme maintenant quand le nombre de vies est à 0.

**Comment by cakeisalie5** [comment]
t'es mon gars sûr, je l'savais
